services:


  backend:
    build:
      context: ./streetsense_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'

  frontend:
    build:
      context: .
    command: npm run dev -- --host
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data:
