# Generated by Django 4.2.16 on 2024-11-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_crimereport_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
