# Generated by Django 3.2.25 on 2024-10-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_crimereport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='date_occurred',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
