# Generated by Django 3.2.25 on 2024-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_crimereport_date_occurred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='type',
            field=models.TextField(default='Disturbance'),
        ),
    ]
