# Use the official Python image with the desired Python version
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt to container image
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt 

# Copy the rest of the application code
COPY . /app/

# Expose port 8000
EXPOSE 8000

# Run migrations and start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
